global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
# - job_name: geth
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /debug/metrics/prometheus
#   scheme: http
#   static_configs:
#   - targets:
#     - "localhost:6060"
- job_name: 'geth_node'
  metrics_path: /debug/metrics/prometheus
  static_configs:
  - targets: ["172.17.0.1:6060"]
